"""Patch wardrobe_manager.py: replace recommend_daily_outfit with GPS + layer version."""
import sys, re

sys.stdout.reconfigure(encoding='utf-8')
content = open('wardrobe_manager.py', encoding='utf-8').read()

old_start = content.find('def recommend_daily_outfit(')
old_end   = content.find('\n\n\n# \u2500\u2500\u2500 PREFERENCE', old_start)

print(f'Replacing chars {old_start}..{old_end}')

new_block = (
    "def recommend_daily_outfit(user_id: str = 'default', gender: str = 'unisex',\n"
    "                           lat: float = None, lon: float = None) -> Dict:\n"
    "    \"\"\"\n"
    "    G\u1ee3i \u00fd outfit h\u00f4m nay d\u1ef1a tr\u00ean th\u1eddi ti\u1ebft GPS + layer.\n"
    "    \"\"\"\n"
    "    weather = get_current_weather(lat=lat, lon=lon)\n"
    "    temp    = weather.get('temp', 28)\n"
    "    profile = get_weather_profile(temp)\n"
    "    rules   = WEATHER_OUTFIT_RULES.get(profile, WEATHER_OUTFIT_RULES['warm'])\n"
    "\n"
    "    conn = get_db()\n"
    "    try:\n"
    "        rows = conn.execute(\"\"\"\n"
    "            SELECT * FROM wardrobe_items\n"
    "            WHERE user_id = ?\n"
    "              AND (gender = ? OR gender = 'unisex')\n"
    "              AND skip_count <= 3\n"
    "            ORDER BY weight DESC, RANDOM()\n"
    "            LIMIT 50\n"
    "        \"\"\", (user_id, gender)).fetchall()\n"
    "\n"
    "        if not rows:\n"
    "            return {\n"
    "                'outfit': [], 'layers': [],\n"
    "                'weather': weather,\n"
    "                'message': 'T\u1ee7 \u0111\u1ed3 ch\u01b0a c\u00f3 qu\u1ea7n \u00e1o. H\u00e3y upload m\u1ed9t s\u1ed1 m\u00f3n \u0111\u1ea7u ti\u00ean!',\n"
    "                'weather_profile': profile,\n"
    "            }\n"
    "\n"
    "        items = [dict(r) for r in rows]\n"
    "        for it in items:\n"
    "            it['tags'] = json.loads(it.get('tags', '[]'))\n"
    "\n"
    "        by_cat = {}\n"
    "        for item in items:\n"
    "            cat = item.get('category', 'kh\u00e1c')\n"
    "            by_cat.setdefault(cat, []).append(item)\n"
    "\n"
    "        # Layer definitions\n"
    "        LAYER_DEFS = [\n"
    "            {'layer': 1, 'label': 'Qu\u1ea7n / V\u00e1y',          'cats': ['qu\u1ea7n jean', 'qu\u1ea7n t\u00e2y', 'qu\u1ea7n short', 'qu\u1ea7n jogger', 'v\u00e1y ng\u1eafn', 'v\u00e1y d\u00e0i', '\u0111\u1ea7m', 'qu\u1ea7n legging']},\n"
    "            {'layer': 2, 'label': '\u00c1o l\u00f3t / \u00c1o c\u01a1 b\u1ea3n', 'cats': ['\u00e1o thun', '\u00e1o s\u01a1 mi']},\n"
    "            {'layer': 3, 'label': '\u00c1o ngo\u00e0i / Layer',   'cats': ['\u00e1o kho\u00e1c', '\u00e1o blazer', '\u00e1o len', '\u00e1o hoodie']},\n"
    "            {'layer': 4, 'label': 'Gi\u00e0y / D\u00e9p',         'cats': ['gi\u00e0y sneaker', 'gi\u00e0y cao g\u00f3t', 'gi\u00e0y boots', 'gi\u00e0y loafer']},\n"
    "            {'layer': 5, 'label': 'Ph\u1ee5 ki\u1ec7n',           'cats': ['t\u00fai x\u00e1ch', 'balo', 'm\u0169', 'th\u1eaft l\u01b0ng', 'kh\u0103n', 'ph\u1ee5 ki\u1ec7n kh\u00e1c']},\n"
    "        ]\n"
    "\n"
    "        outfit_layers = []\n"
    "        selected_items = []\n"
    "\n"
    "        for layer_def in LAYER_DEFS:\n"
    "            for cat in layer_def['cats']:\n"
    "                if cat in by_cat and by_cat[cat]:\n"
    "                    valid = [i for i in by_cat[cat] if cat not in rules.get('avoid', [])]\n"
    "                    if valid:\n"
    "                        best = dict(max(valid, key=lambda x: x.get('weight', 1.0)))\n"
    "                        best['_layer'] = layer_def['layer']\n"
    "                        best['_layer_label'] = layer_def['label']\n"
    "                        outfit_layers.append({\n"
    "                            'layer': layer_def['layer'],\n"
    "                            'label': layer_def['label'],\n"
    "                            'item': best,\n"
    "                        })\n"
    "                        selected_items.append(best)\n"
    "                        break\n"
    "\n"
    "        ai_tips = _generate_outfit_tips(outfit_layers, weather, rules)\n"
    "\n"
    "        return {\n"
    "            'outfit':          selected_items[:5],\n"
    "            'layers':          outfit_layers,\n"
    "            'weather':         weather,\n"
    "            'weather_profile': profile,\n"
    "            'layers_needed':   rules['layers'],\n"
    "            'suggested_materials': rules['materials'],\n"
    "            'avoid':           rules['avoid'],\n"
    "            'ai_tips':         ai_tips,\n"
    "            'message':         f\"Outfit cho {weather.get('description', '')} ({temp}\u00b0C) t\u1ea1i {weather.get('city', 'v\u1ecb tr\u00ed c\u1ee7a b\u1ea1n')}\",\n"
    "        }\n"
    "\n"
    "    finally:\n"
    "        conn.close()\n"
    "\n"
    "\n"
    "def _generate_outfit_tips(layers: List[Dict], weather: Dict, rules: Dict) -> str:\n"
    "    \"\"\"T\u1ea1o g\u1ee3i \u00fd mix&match rule-based kh\u00f4ng c\u1ea7n API call.\"\"\"\n"
    "    temp   = weather.get('temp', 28)\n"
    "    desc   = weather.get('description', '')\n"
    "    avoid  = rules.get('avoid', [])\n"
    "    mats   = rules.get('materials', [])\n"
    "    colors = [l['item'].get('color', '') for l in layers if l.get('item')]\n"
    "    tips   = []\n"
    "    if temp >= 30:\n"
    "        tips.append(f\"\u2600\ufe0f Tr\u1eddi {desc} ({temp}\u00b0C) \u2014 ch\u1ecdn ch\u1ea5t li\u1ec7u {', '.join(mats[:2])} \u0111\u1ec3 tho\u00e1ng m\u00e1t.\")\n"
    "    elif temp >= 24:\n"
    "        tips.append(f\"\u26c5 Th\u1eddi ti\u1ebft \u1ea5m \u00e1p ({temp}\u00b0C) \u2014 l\u00fd t\u01b0\u1edfng cho outfit 1 l\u1edbp nh\u1eb9.\")\n"
    "    elif temp >= 18:\n"
    "        tips.append(f\"Mat troi ({temp}\u00b0C) \u2014 th\u00eam \u00e1o kho\u00e1c m\u1ecfng \u0111\u1ec3 \u0111\u1eb9p h\u01a1n.\")\n"
    "    else:\n"
    "        tips.append(f\"[Lanh] Tr\u1eddi l\u1ea1nh ({temp}\u00b0C) \u2014 m\u1eb7c nhi\u1ec1u l\u1edbp, \u01b0u ti\u00ean {', '.join(mats[:2])}.\")\n"
    "    if avoid:\n"
    "        tips.append(f\"\u26a0\ufe0f H\u00f4m nay n\u00ean tr\u00e1nh: {', '.join(avoid)}.\")\n"
    "    valid_colors = [c for c in colors if c]\n"
    "    if len(valid_colors) >= 2:\n"
    "        tips.append(f\"\ud83c\udfa8 G\u1ee3i \u00fd ph\u1ed1i m\u00e0u: {valid_colors[0]} + {valid_colors[1]}.\")\n"
    "    return ' '.join(tips)\n"
)

new_content = content[:old_start] + new_block + content[old_end:]
open('wardrobe_manager.py', 'w', encoding='utf-8').write(new_content)
print('OK - patched recommend_daily_outfit with GPS + layers + _generate_outfit_tips')
